language: node_js
node_js:
  - "8"
before_install: 'echo "bruce test:> before install"'
before_script: "npm run lint"
after_success: "npm run build && ls"
after_failure: 'echo "bruce test:> script failure"'
after_script: 'echo "bruce test:> after script"'
